name: CI - Build and Test Go Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test on Go 1.20

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.0'
          cache: true

      - name: Ensure go.mod and go.sum are clean
        run: go mod tidy

      - name: Build all packages
        run: go build -v ./...

      - name: Run all tests
        run: go test -v ./...
